export const EventErrorCodes = {
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",

  MANAGER_NOT_ALLOWED: "MANAGER_NOT_ALLOWED",
  // EVENT_UPDATE_FAILED: "EVENT_UPDATE_FAILED",
  // EVENT_CREATE_FAILED: "EVENT_CREATE_FAILED",
  // EVENT_DELETE_FAILED: "EVENT_DELETE_FAILED",
  // EVENT_TICKET_TYPE_NOT_FOUND: "EVENT_TICKET_TYPE_NOT_FOUND",
  // EVENT_TICKET_TYPE_UPDATE_FAILED: "EVENT_TICKET_TYPE_UPDATE_FAILED",
  // EVENT_TICKET_TYPE_CREATE_FAILED: "EVENT_TICKET_TYPE_CREATE_FAILED",
  // EVENT_TICKET_TYPE_DELETE_FAILED: "EVENT_TICKET_TYPE_DELETE_FAILED",
  // EVENT_ORGANIZER_NOT_FOUND: "EVENT_ORGANIZER_NOT_FOUND",
  // EVENT_CATEGORY_NOT_FOUND: "EVENT_CATEGORY_NOT_FOUND",
  // EVENT_SUBCATEGORY_NOT_FOUND: "EVENT_SUBCATEGORY_NOT_FOUND",
} as const;

export class EventError extends Error {
  code: string;
  metadata?: any;

  constructor(code: string, message: string, metadata?: any) {
    super(message);
    this.name = "EventError";
    this.code = code;
    this.metadata = metadata;
  }
}